gestiondustock_gestion_magasins:
  path: gestiondustock/gestion/magasins
  methods: [ GET,POST ]
  defaults:
    _controller: 'GestionDuStock\Controller\GestionMagasinsController::editAction'
    _legacy_controller: 'AdminGestionDuStockMagasins'
    _legacy_link: 'AdminGestionDuStockMagasins'

gestiondustock_gestion_stock_magasins:
  path: gestiondustock/stock/magasins
  methods: [ GET,POST ]
  defaults:
    _controller: 'GestionDuStock\Controller\GestionStockController::editAction'
    _legacy_controller: 'AdminGestionDuStock'
    _legacy_link: 'AdminGestionDuStock'

gestiondustock_gestion_magasins_add:
    path: gestiondustock/gestion/magasins/add
    methods: [ GET,POST ]
    defaults:
      { _controller: 'GestionDuStock\Controller\GestionMagasinsController::addOrUpdateMagasins' }

gestiondustock_gestion_magasins_update:
    path: gestiondustock/gestion/magasins/update/{id}
    methods: [ GET,POST ]
    defaults:
      { _controller: 'GestionDuStock\Controller\GestionMagasinsController::addOrUpdateMagasins' }

gestiondustock_gestion_magasins_edit:
    path: gestiondustock/gestion/magasins/edit/{id}
    methods: [ GET,POST ]
    defaults:
      { _controller: 'GestionDuStock\Controller\GestionMagasinsController::editMagasins' }

gestiondustock_gestion_magasins_delete:
    path: gestiondustock/gestion/magasins/delete/{id}
    methods: [ GET,POST ]
    defaults:
      { _controller: 'GestionDuStock\Controller\GestionMagasinsController::deleteMagasins' }